# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: assert_not magic?
email: ryan@thepalos.com
description: > # this means to ignore newlines until "baseurl:"
  Programming blog by Ryan Palo.  Code is not magic, and anyone can do it.  Python, Ruby, JavaScript, shell scripting, systems, the web, and more!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://assertnotmagic.com" # the base hostname & protocol for your site
twitter_username: paytastic
github_username:  rpalo
permalink: pretty

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

sass:
  style: compressed

# Other configurations
timezone: America/Los_Angeles

# Images
cloudinary:
  cloud_name: duninnjce
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"

# File Inclusions
exclude: [
  README.md,
  blog.sublime-project,
  blog.sublime-workspace,
  deploy.sh,
  maketag.sh,
  purge_cache.sh,
  secrets.sh,
  notes.md,
  .gitignore,
  Gemfile,
  Gemfile.lock,
  cloudinary.yml,
]

# Gems
plugins:
- jekyll-autoprefixer
