---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: src/tags
  label: Tags
  create: all
  match: "**/*.md"
  templates:
  - tag-template
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: src/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
